#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_DIR="$PROJECT_DIR/backend/config"
ENV_FILE="$PROJECT_DIR/.env"

echo "=== LastSaaS Setup ==="
echo ""

# Determine which environment to configure
read -rp "Environment [dev]: " ENV
ENV="${ENV:-dev}"

EXAMPLE_FILE="$CONFIG_DIR/${ENV}.example.yaml"
OUTPUT_FILE="$CONFIG_DIR/${ENV}.yaml"

if [ ! -f "$EXAMPLE_FILE" ]; then
    echo "Error: Example config not found at $EXAMPLE_FILE"
    exit 1
fi

if [ -f "$OUTPUT_FILE" ]; then
    read -rp "$OUTPUT_FILE already exists. Overwrite? [y/N]: " OVERWRITE
    if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
        echo "Skipping config generation."
        exit 0
    fi
fi

echo ""
echo "--- Database ---"
echo "The database name is the project identity. Two projects sharing"
echo "the same database name intentionally share the same user base."
echo ""
read -rp "Database Name [lastsaas-dev]: " DATABASE_NAME
DATABASE_NAME="${DATABASE_NAME:-lastsaas-dev}"
echo ""
read -rp "MongoDB URI [mongodb://localhost:27017]: " MONGODB_URI
MONGODB_URI="${MONGODB_URI:-mongodb://localhost:27017}"

echo ""
echo "--- JWT Secrets ---"
echo "Generating random JWT secrets..."
JWT_ACCESS_SECRET=$(openssl rand -hex 32)
JWT_REFRESH_SECRET=$(openssl rand -hex 32)
echo "  Access secret:  ${JWT_ACCESS_SECRET:0:12}..."
echo "  Refresh secret: ${JWT_REFRESH_SECRET:0:12}..."

echo ""
echo "--- Google OAuth (optional, press Enter to skip) ---"
read -rp "Google Client ID: " GOOGLE_CLIENT_ID
read -rp "Google Client Secret: " GOOGLE_CLIENT_SECRET

echo ""
echo "--- Resend Email (optional, press Enter to skip) ---"
read -rp "Resend API Key: " RESEND_API_KEY

echo ""
echo "--- App Settings ---"
read -rp "App Name [LastSaaS]: " APP_NAME
APP_NAME="${APP_NAME:-LastSaaS}"
read -rp "From Email [noreply@yourdomain.com]: " FROM_EMAIL
FROM_EMAIL="${FROM_EMAIL:-noreply@yourdomain.com}"

# Write .env file
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date)
DATABASE_NAME=$DATABASE_NAME
MONGODB_URI=$MONGODB_URI
JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET
JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
RESEND_API_KEY=$RESEND_API_KEY
APP_NAME=$APP_NAME
FROM_EMAIL=$FROM_EMAIL
FROM_NAME=$APP_NAME
SERVER_HOST=localhost
SERVER_PORT=4290
FRONTEND_URL=http://localhost:4280
VITE_PORT=4280
VITE_API_URL=http://localhost:4290
GOOGLE_REDIRECT_URL=http://localhost:4290/api/auth/google/callback
EOF

echo ""
echo "Wrote environment variables to $ENV_FILE"

# Copy example config to actual config
cp "$EXAMPLE_FILE" "$OUTPUT_FILE"
echo "Copied $EXAMPLE_FILE -> $OUTPUT_FILE"

# Validate MongoDB connection
echo ""
echo "--- Validating MongoDB connection ---"
if command -v mongosh &> /dev/null; then
    if mongosh "$MONGODB_URI" --eval "db.adminCommand('ping')" --quiet 2>/dev/null; then
        echo "MongoDB connection: OK"
    else
        echo "Warning: Could not connect to MongoDB at $MONGODB_URI"
        echo "  Make sure MongoDB is running before starting the server."
    fi
elif command -v mongo &> /dev/null; then
    if mongo "$MONGODB_URI" --eval "db.adminCommand('ping')" --quiet 2>/dev/null; then
        echo "MongoDB connection: OK"
    else
        echo "Warning: Could not connect to MongoDB at $MONGODB_URI"
        echo "  Make sure MongoDB is running before starting the server."
    fi
else
    echo "Note: mongosh not found, skipping MongoDB connection check."
    echo "  Make sure MongoDB is accessible at $MONGODB_URI before starting."
fi

echo ""
echo "=== Setup Complete ==="
echo ""
echo "To start the server:"
echo "  source $ENV_FILE"
echo "  cd $PROJECT_DIR/backend"
echo "  go run ./cmd/server"
echo ""
echo "Or with explicit env loading:"
echo "  set -a && source $ENV_FILE && set +a && cd $PROJECT_DIR/backend && go run ./cmd/server"
